# String targetUrl = "https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=flw&lang=tc";

api: 
  jsonplaceholder:
    domain: "data.weather.gov.hk"
    endpoints: 
      traditionalChinese: "/weatherAPI/opendata/weather.php?dataType=flw&lang=tc"
      english: "/weatherAPI/opendata/weather.php?dataType=flw&lang=en"